# Generated by Django 5.2.4 on 2025-08-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_target_book_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='target',
        ),
    ]
