# Generated by Django 5.2.4 on 2025-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_location_book_publisher_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='이용자 대상 주기 전거표')),
            ],
            options={
                'verbose_name': '521 전거',
            },
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': '이용자대상', 'verbose_name_plural': '이용자대상'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='marc',
            name='content',
        ),
        migrations.AddField(
            model_name='marc',
            name='field_020',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='020'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_020_set',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='020(세트)'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_022',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='022'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_052',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='052'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_090',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='090'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_245',
            field=models.TextField(blank=True, null=True, verbose_name='245'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_246_origin',
            field=models.TextField(blank=True, null=True, verbose_name='246(원표제)'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_246_same',
            field=models.TextField(blank=True, null=True, verbose_name='246(대등표제)'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_250',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='250'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_260',
            field=models.TextField(blank=True, null=True, verbose_name='260'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_300',
            field=models.TextField(blank=True, null=True, verbose_name='300'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_310',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='310'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_342',
            field=models.TextField(blank=True, null=True, verbose_name='342'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_490',
            field=models.TextField(blank=True, null=True, verbose_name='490'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_500',
            field=models.TextField(blank=True, null=True, verbose_name='500'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_502',
            field=models.TextField(blank=True, null=True, verbose_name='502'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_504',
            field=models.TextField(blank=True, null=True, verbose_name='504'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_541',
            field=models.TextField(blank=True, null=True, verbose_name='541'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_546',
            field=models.TextField(blank=True, null=True, verbose_name='546'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_586',
            field=models.TextField(blank=True, null=True, verbose_name='586'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_590',
            field=models.TextField(blank=True, null=True, verbose_name='590'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_600',
            field=models.TextField(blank=True, null=True, verbose_name='600'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_610',
            field=models.TextField(blank=True, null=True, verbose_name='610'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_647',
            field=models.TextField(blank=True, null=True, verbose_name='647'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_650',
            field=models.TextField(blank=True, null=True, verbose_name='650'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_653',
            field=models.TextField(blank=True, null=True, verbose_name='653'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_655',
            field=models.TextField(blank=True, null=True, verbose_name='655'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_700',
            field=models.TextField(blank=True, null=True, verbose_name='700'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_710',
            field=models.TextField(blank=True, null=True, verbose_name='710'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_720',
            field=models.TextField(blank=True, null=True, verbose_name='720'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_730',
            field=models.TextField(blank=True, null=True, verbose_name='730'),
        ),
        migrations.AddField(
            model_name='marc',
            name='field_856',
            field=models.TextField(blank=True, null=True, verbose_name='856'),
        ),
        migrations.AddField(
            model_name='target',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='books.book'),
        ),
        migrations.AddField(
            model_name='target',
            name='field_521',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='521(이용자대상주기)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('대출가능', '대출가능'), ('대출중', '대출중'), ('예약중', '예약중'), ('대출불가', '대출불가')], default='대출가능', max_length=20),
        ),
        migrations.AlterField(
            model_name='marc',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marc', to='books.book'),
        ),
        migrations.CreateModel(
            name='Curation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_500_curation', models.TextField(verbose_name='500(큐레이션 주기)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curations', to='books.book')),
            ],
            options={
                'verbose_name': '큐레이션',
                'verbose_name_plural': '큐레이션',
            },
        ),
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_targets', to='books.targetname'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('book', 'target'), name='uq_target_book_authority'),
        ),
    ]
