# Generated by Django 5.2.4 on 2025-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_location_book_publisher_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='curation_cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='target_cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
