# Generated by Django 5.2.4 on 2025-08-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_targetname_alter_target_options_remove_book_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curation',
            options={'verbose_name': 'Curation', 'verbose_name_plural': 'Curation'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Target', 'verbose_name_plural': 'Target'},
        ),
    ]
