# Generated by Django 5.2.4 on 2025-08-21 14:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_curation_options_alter_target_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='marc',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='MARC JSON'),
        ),
    ]
