# Generated by Django 5.2.4 on 2025-08-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_marc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('AVAILABLE', '대출가능'), ('RENTED', '대출중'), ('RESERVED', '예약중'), ('UNAVAILABLE', '대출불가')], default='대출가능', max_length=20),
        ),
    ]
