# Generated by Django 5.2.4 on 2025-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_image_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marc',
            name='field_342',
        ),
        migrations.AddField(
            model_name='marc',
            name='field_362',
            field=models.TextField(blank=True, null=True, verbose_name='362'),
        ),
    ]
