# Generated by Django 5.2.4 on 2025-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_marc_field_342_marc_field_362'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curation',
            options={'verbose_name': 'Curation'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Target'},
        ),
        migrations.AlterModelOptions(
            name='targetname',
            options={'verbose_name': 'TargetName'},
        ),
        migrations.AlterField(
            model_name='targetname',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='이용자대상주기'),
        ),
    ]
