# Generated by Django 5.2.4 on 2025-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_curation_options_alter_target_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marc',
            name='field_056',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='056'),
        ),
    ]
