# Generated by Django 5.2.4 on 2025-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_marc_field_056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_020',
            field=models.TextField(blank=True, null=True, verbose_name='020'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_020_set',
            field=models.TextField(blank=True, null=True, verbose_name='020(세트)'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_022',
            field=models.TextField(blank=True, null=True, verbose_name='022'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_052',
            field=models.TextField(blank=True, null=True, verbose_name='052'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_056',
            field=models.TextField(blank=True, null=True, verbose_name='056'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_090',
            field=models.TextField(blank=True, null=True, verbose_name='090'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_250',
            field=models.TextField(blank=True, null=True, verbose_name='250'),
        ),
        migrations.AlterField(
            model_name='marc',
            name='field_310',
            field=models.TextField(blank=True, null=True, verbose_name='310'),
        ),
    ]
