# Generated by Django 5.2.4 on 2025-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_location_alter_marc_field_020_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='callnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
