# Generated by Django 5.2.4 on 2025-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_callnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='targetname',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='이용자대상'),
        ),
    ]
