# Generated by Django 5.2.4 on 2025-08-20 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_curation_options_alter_target_options'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(condition=models.Q(('is_returned', False)), fields=('book', 'is_returned'), name='uq_active_rental_per_book'),
        ),
    ]
