# Generated by Django 5.2.4 on 2025-08-20 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_location_book_publisher_alter_book_author'),
        ('reservations', '0003_remove_reservation_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_due_dat_dfcdee_idx',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='canceled_at',
            new_name='cancel_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='reservation_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status', 'due_date'], name='reservation_user_id_770bed_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['due_date'], name='reservation_due_dat_09d446_idx'),
        ),
    ]
