# Generated by Django 5.2.4 on 2025-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_user_id_770bed_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_due_dat_09d446_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '예약중'), ('CANCELED', '예약취소'), ('EXPIRED', '예약만료')], default='ACTIVE', max_length=10),
        ),
    ]
