# Generated by Django 5.2.4 on 2025-08-25 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_book_status'),
        ('reservations', '0005_remove_reservation_reservation_user_id_770bed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'book'), name='uq_active_reservation_per_user_book'),
        ),
    ]
