# Generated by Django 5.2.4 on 2025-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '예약중'), ('CANCELED', '예약취소'), ('EXPIRED', '예약만료')], default='ACTIVE', max_length=10),
        ),
    ]
